USE [master]
GO
/****** Object:  Database [TODO]    Script Date: 5/17/2022 5:27:52 PM ******/
CREATE DATABASE [TODO]
GO
ALTER DATABASE [TODO] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TODO].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TODO] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TODO] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TODO] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TODO] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TODO] SET ARITHABORT OFF 
GO
ALTER DATABASE [TODO] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [TODO] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TODO] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TODO] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TODO] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TODO] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TODO] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TODO] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TODO] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TODO] SET  ENABLE_BROKER 
GO
ALTER DATABASE [TODO] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TODO] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TODO] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TODO] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TODO] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TODO] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TODO] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TODO] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [TODO] SET  MULTI_USER 
GO
ALTER DATABASE [TODO] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TODO] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TODO] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TODO] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TODO] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [TODO] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [TODO] SET QUERY_STORE = OFF
GO
USE [TODO]
GO
/****** Object:  UserDefinedFunction [dbo].[DistanceKM]    Script Date: 5/17/2022 5:27:52 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

Create Function [dbo].[DistanceKM] 
( 
      @Lat1 Float(18),  
      @Lat2 Float(18), 
      @Long1 Float(18), 
      @Long2 Float(18)
)
Returns Float(18)
AS
Begin
      Declare @R Float(8); 
      Declare @dLat Float(18); 
      Declare @dLon Float(18); 
      Declare @a Float(18); 
      Declare @c Float(18); 
      Declare @d Float(18);
      Set @R =  6367.45
            --Miles 3956.55  
            --Kilometers 6367.45 
            --Feet 20890584 
            --Meters 6367450 


      Set @dLat = Radians(@lat2 - @lat1);
      Set @dLon = Radians(@long2 - @long1);
      Set @a = Sin(@dLat / 2)  
                 * Sin(@dLat / 2)  
                 + Cos(Radians(@lat1)) 
                 * Cos(Radians(@lat2))  
                 * Sin(@dLon / 2)  
                 * Sin(@dLon / 2); 
      Set @c = 2 * Asin(Min(Sqrt(@a))); 

      Set @d = @R * @c; 
      Return @d; 

End
GO
/****** Object:  UserDefinedFunction [dbo].[fncCalcDistanceKM]    Script Date: 5/17/2022 5:27:52 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[fncCalcDistanceKM](@Lat1 FLOAT(18), @LAT2 FLOAT(18),
	@LONG1 FLOAT(18),
	@LONG2 FLOAT(18)
)
returns FLOAT(18) as
begin
declare @R FLOAT(18)
DECLARE @A FLOAT(18)
DECLARE @C FLOAT(18)
DECLARE @D FLOAT(18)
set @R = 6367.45;

DECLARE @DLAT FLOAT(18)
DECLARE @DLON FLOAT(18)
SET @DLAT = RADIANS(@LAT2 - @Lat1);
SET @DLON = RADIANS(@LONG2 - @Long1);

SET @LAT1 = @LAT1 * PI() / 180;
SET @LAT2 = @LAT2 * PI() / 180;


SET @A = SIN(@DLAT/2) * SIN(@DLAT/2) + COS(@LAT1) * COS(@LAT2)
* SIN(@DLON / 2) * SIN(@DLON / 2);


SET @C = 2*Asin(Min(Sqrt(@a))); 

SET @D = @R * @C
RETURN @D

END
GO
/****** Object:  UserDefinedFunction [dbo].[fncCalcDistanceMiles]    Script Date: 5/17/2022 5:27:52 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[fncCalcDistanceMiles](@Lat1 decimal, @LAT2 decimal,
	@LONG1 DECIMAL,
	@LONG2 DECIMAL
)
returns decimal as
begin
declare @R decimal
DECLARE @C DECIMAL
DECLARE @D DECIMAL
set @R = 6371.45;

SET @LAT1 = @LAT1 * PI() / 180;
SET @LONG1 = @LONG1 * PI() / 180;
SET @LAT2 = @LAT1 * PI() / 180;
SET @LONG2 = @LONG2 * PI() / 180;

DECLARE @DELTA1 DECIMAL
DECLARE @DELTA2 DECIMAL
SET @DELTA1 = @LAT2 - @Lat1;
SET @DELTA2 = @LONG2 - @Long1;

DECLARE @A DECIMAL
SET @A = SIN(@DELTA1/2) * SIN(@DELTA1/2) + COS(@LAT1) * COS(@LAT2)
* SIN(@DELTA2 / 2) * SIN(@DELTA2 / 2);


SET @C = 2*Asin(Min(Sqrt(@a))); 

SET @D = @R * @C
RETURN @D

END
GO
/****** Object:  UserDefinedFunction [dbo].[FUNC_JOINTODOINFO]    Script Date: 5/17/2022 5:27:52 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE FUNCTION [dbo].[FUNC_JOINTODOINFO] (
	@ID INT,
	@TITLE NVARCHAR(50),
	@ISCOMPLETE BIT
)
RETURNS NVARCHAR(200)
AS 
BEGIN 
IF (@ID % 2 = 0) 
	RETURN (SELECT CAST(@ID AS VARCHAR) + ':' + @TITLE + 'EVEN')

RETURN (SELECT CAST(@ID AS VARCHAR) + ':' + @TITLE + 'ODD')
END
GO
/****** Object:  UserDefinedFunction [dbo].[FUNC_SUM]    Script Date: 5/17/2022 5:27:52 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[FUNC_SUM](
	@NUM1 INT,
	@NUM2 INT
)
RETURNS INT
BEGIN
	DECLARE @RESULT INT
	SET @RESULT = @NUM1 + @NUM2
	RETURN @RESULT
END
GO
/****** Object:  Table [dbo].[TODOITEM]    Script Date: 5/17/2022 5:27:52 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TODOITEM](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[TITLE] [nvarchar](100) NULL,
	[ISCOMPLETE] [smallint] NULL,
 CONSTRAINT [PK__TODOITEM__3214EC2794E522AB] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  UserDefinedFunction [dbo].[FUNC_TODOINFO]    Script Date: 5/17/2022 5:27:52 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[FUNC_TODOINFO]()
RETURNS TABLE
AS 
RETURN (SELECT* FROM TODOITEM)
GO
SET IDENTITY_INSERT [dbo].[TODOITEM] ON 
GO
INSERT [dbo].[TODOITEM] ([ID], [TITLE], [ISCOMPLETE]) VALUES (1, N'HOMEWORK', 1)
GO
INSERT [dbo].[TODOITEM] ([ID], [TITLE], [ISCOMPLETE]) VALUES (2, N'HouseWork', 1)
GO
INSERT [dbo].[TODOITEM] ([ID], [TITLE], [ISCOMPLETE]) VALUES (3, N'working', 0)
GO
INSERT [dbo].[TODOITEM] ([ID], [TITLE], [ISCOMPLETE]) VALUES (4, N'Cleaning', 1)
GO
INSERT [dbo].[TODOITEM] ([ID], [TITLE], [ISCOMPLETE]) VALUES (6, N'Doing something', 0)
GO
INSERT [dbo].[TODOITEM] ([ID], [TITLE], [ISCOMPLETE]) VALUES (7, N'DOING-HOMEWORK', 0)
GO
SET IDENTITY_INSERT [dbo].[TODOITEM] OFF
GO
/****** Object:  StoredProcedure [dbo].[PROC_ADDTODO]    Script Date: 5/17/2022 5:27:52 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[PROC_ADDTODO](
	@TITLE NVARCHAR(50),
	@COMMENT NVARCHAR(50)
) 
AS
BEGIN
	INSERT INTO DBO.TODOITEM
	VALUES
	(@TITLE + '-' +  @COMMENT, 0)

END
GO
/****** Object:  StoredProcedure [dbo].[PROC_SUM]    Script Date: 5/17/2022 5:27:52 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[PROC_SUM] @NUM1 INT, @NUM2 INT, @SUM INT OUTPUT
AS 
BEGIN
	SET @SUM  = DBO.FUNC_SUM(@NUM1, @NUM2)
END
GO
USE [master]
GO
ALTER DATABASE [TODO] SET  READ_WRITE 
GO
